name: Tests
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Versions
        run: |
          node -v
          google-chrome --version
          chromedriver -v

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Yarn test
        uses: GabrielBB/xvfb-action@v1.2

        with:
          run: yarn test
